({ name:"Google credentials",
  elements:{ id:{ name:"Id",
      type:"string" },
    token:{ name:"Token",
      type:"string" },
    email:{ name:"Email",
      type:"email" },
    name:{ name:"Name",
      type:"string" } },
  key:"google_access" })