({ name:"Simple image reduction",
  ui_opts:{ child_view_type:"pills",
    close:true },
  elements:{ processing:{ name:"Processing",
      ui_opts:{ sliding:true,
        slided:false },
      elements:{ debias_flat:{ ui_opts:{ type:"edit" },
          type:"bool",
          name:"Substract bias from flat-field",
          value:true },
        normalize_flat:{ ui_opts:{ type:"edit" },
          type:"bool",
          name:"Normalize flat",
          value:true },
        start:{ name:"Reduce image",
          type:"action" } } },
    input:{ name:"Input",
      ui_opts:{ sliding:true,
        slided:false },
      elements:{ bias:{ name:"Bias",
          ui_opts:{ sliding:true,
            slided:false },
          type:"image" },
        flat:{ name:"Flat-field",
          ui_opts:{ sliding:true,
            slided:false },
          type:"image" },
        science:{ name:"Science",
          ui_opts:{ sliding:true,
            slided:false },
          type:"image" } } },
    output:{ name:"Output",
      ui_opts:{ sliding:true,
        slided:false },
      elements:{ reduced_science:{ name:"Reduced science",
          ui_opts:{ sliding:true,
            slided:false },
          type:"image" } } } },
  key:"image_reduction",
  widget_builder:function (ok, fail){ ok(); } })