({ ui_opts:{ type:"short",
    label:true },
  name:"Image dimensions",
  tip:"Dimension of the image in pixels",
  type:"labelled_vector",
  min:"0",
  max:"65536",
  step:"1",
  value:[ 0,
    0 ],
  value_labels:[ "Dx",
    "Dy" ],
  key:"image_dimensions",
  widget_builder:function (ok, fail){ ok(); } })