({ ui_opts:{ root_classes:[ "container-fluid" ],
    fa_icon:"book",
    child_view_type:"tabbed",
    intro_stick:true },
  name:"Webspectro user manual",
  intro:"<i class='fa fa-exclamation-triangle text-danger'></i> WebSpectro should be easy to use and intuitive! ",
  elements:{ spectro_win:{ name:"Spectrograph window",
      type:"html",
      ui_opts:{ fa_icon:"line-chart" },
      value:"<p>The spectrograph window is composed of two main panels. The <strong>Video</strong> panel (left) controls the image acquisition and processing while the <strong>Spectro</strong> panel (on the right) is the monodimensional spectrum interface.</p>",
      elements:{ video:{ name:"Video panel",
          intro:"The video panel",
          ui_opts:{ fa_icon:"camera" },
          elements:{ device:{ ui_opts:{ fa_icon:"camera-retro" },
              type:"media",
              name:"Device configuration",
              elements:{} } } },
        spectro:{ name:"Spectro panel",
          ui_opts:{ fa_icon:"line-chart" } } } },
    editing:{ name:"Saved spectra window",
      ui_opts:{ fa_icon:"folder" } },
    calibration:{ name:"Calibration window",
      ui_opts:{ fa_icon:"calculator" } } },
  key:"manual",
  widget_builder:function (ok, fail){ ok(); } })