({ name:"StudyMusic",
  subtitle:"Learn music in tempo. Yeah ! ",
  ui_opts:{ root_classes:[ "container-fluid" ],
    child_view_type:"tabbed",
    fa_icon:"leaf" },
  toolbar:{ elements:{ file_menu:{ name:"Lessons",
        elements:{ open:{ name:"Lesson1" },
          load:{ name:"Lesson2" },
          close:{ name:"Lesson3" } } } } },
  elements:{ lessons:{ name:"My lessons",
      subtitle:"Manage your lessons here" },
    time:{ name:"Time organization",
      subtitle:"Manage your lessons here" },
    account:{ name:"User account",
      subtitle:"Setup your user account",
      type:"user" } },
  key:"music_app" })