({ name:"<span style=\"color: springgreen;\">ॐ</span> <strong> Sadira </strong>",
  ui_opts:{ root_classes:[ "container-fluid left" ],
    intro_stick:true },
  toolbar:{ sadira_tools:{ elements:{ demos:{ name:"Demos",
          elements:{ xd1:{ name:"XD-1",
              type:"xd1",
              link:true },
            minispectro:{ name:"Minispectro",
              type:"videocap",
              link:true } } },
        toolkit:{ name:"Web Toolkit",
          elements:{ demo:{ name:"Toolkit sandbox",
              type:"ui_demo" },
            tuto:{ name:"Sadira Toolkit tutorial",
              type:"stk_tutorial" },
            tlist:{ name:"Templates",
              type:"dbtemplates" } } },
        database:{ name:"Dev",
          elements:{ browser:{ name:"Database browser",
              type:"db_browser" },
            sock_mgr:{ type:"socket_manager" },
            nunki:{ type:"nunki",
              link:true } } } } } },
  elements:{ welcome:{ subtitle:"INAF/IASF-Bologna — <i>Astro-web-software </i>",
      name:"Sadira",
      type:"html",
      url:"/sadira/welcome.html",
      ui_opts:{ icon:"/sadira/icons/iasfbo.png" } },
    deps:{ name:"Software deps",
      type:"soft_links",
      ui_opts:{ item_classes:[ "container-fluid" ],
        name_node:"h2" } } },
  key:"sadira_home" })